#!/usr/bin/env python3
from pymongo import MongoClient

def list_databases():
    client = MongoClient('mongodb://localhost:27017')
    databases = client.list_database_names()
    print("Databases:")
    for db in databases:
        print(f"- {db}")

list_databases()
